# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_wle <- function(X_, beta, max_iter = 100L, tol = 1e-10, lower_ext = NA_real_, upper_ext = NA_real_, wle_adj = 1e-8) {
    .Call(`_jmleIRT_estimate_wle`, X_, beta, max_iter, tol, lower_ext, upper_ext, wle_adj)
}

estimate_jmle <- function(X_, max_iter = 1000L, conv = 1e-6, eps = 0.0, bias_correction = FALSE, center = "items", max_update = 1.5, verbose = FALSE, estimatewle = FALSE, wle_adj = 1e-8) {
    .Call(`_jmleIRT_estimate_jmle`, X_, max_iter, conv, eps, bias_correction, center, max_update, verbose, estimatewle, wle_adj)
}

prox_rasch <- function(dat, dat_resp, freq, conv = 0.001, maxiter = 30L) {
    .Call(`_jmleIRT_prox_rasch`, dat, dat_resp, freq, conv, maxiter)
}

